-- ============================================================================
--  Descrizioni dei piatti — dal menu del sito
-- ============================================================================
--
--  129 descrizioni su 225 piatti: le altre sul sito non ce l'hanno
--  (vini, distillati, birre: il nome basta).
--
--  Non servono ai calcoli. Servono a chi compone la ricetta: mentre
--  aggiunge gli ingredienti ha sotto gli occhi cosa c'e' dentro il piatto,
--  invece di andarselo a cercare sul sito e dimenticarne meta'.
--
--  Richiede la migrazione 21. Idempotente: sovrascrive e basta.
-- ============================================================================

set search_path = magazzino, public;

update magazzino.prodotto_venduto p
set descrizione = x.descrizione
from (values
  ('Alta Mora Arrigo 2022', 'Cusumano'),
  ('Altamora Etna Bianco', 'Cusumano'),
  ('Alteni di Brassica – Gaja', 'Gaja — Piemonte – Sauvignon Bianco iconico di Gaja: morbido, intenso, con aromi di frutta esotica e leggere note boisé da affinamento in barrique. Una delle più alte espressioni piemontesi del Sauvignon.'),
  ('Amarone Classico Riserva ''Costasera'' – Masi 2019', 'Masi — Uve: Corvina 70%, Rondinella 15%, Oseleta 10%, Molinara 5%. Affinato 40 mesi in rovere. Profumi intensi di frutta rossa in confettura e sotto spirito, caffè tostato e spezie. Al palato è strutturato, ricco e persistente, con tannino vellutato.'),
  ('Bao burger 1pz', 'Bao a vapore | hamburger di scottona e nobile grasso 70gr | foglia di shiso in tempura | maio al wasabi'),
  ('Bao burger spicy 1pz', 'Bao 35 gr a vapore e leggermente piastrato| burger di scottona bavarese e nobile grasso 70gr | marmellata di cipolla bianca al peperoncino fritto koreano | maio al gochujang | lattuga | salsa burger pepper spicy'),
  ('Bao burger tartufo 1pz', 'Bao a vapore 35gr | burger di scottona bavarese e nobile grasso 70gr | foglia di shiso in tempura | senape al miele e tartufo | scaglie di tartufo fresco'),
  ('Bao burger wagyu tartufo 1pz', 'Il mio primo bao anche su hio oriental ! Bao a vapore | hamburger di wagyu a5 50gr| foglia di shiso in tempura | senape al miele e tartufo | scaglie di tartufo fresco'),
  ('Bao lobster 1pz', 'Bao a vapore con hamburger di crostacei | maionese giapponese aromatizzata al lime e scorza d''arancia | julienne di lattuga | salsa teriyaki'),
  ('Bao smash pastrami spicy 1pz', 'Bao a vapore 35gr | pastrami dierendonck | salsa hio spicy | cipolla caramellata con peperoncino fritto koreano | julienne di lattuga Servito con patatine fritte'),
  ('Barbaresco Gaja 2022', 'Gaja — 100% Nebbiolo Uno dei vini italiani più prestigiosi ed eleganti conosciuti in tutto il mondo. Morbido e vellutato con un bouquet di frutti di bosco, violetta e sfumature di boisé.'),
  ('Barbaresco ‘Serraboella’ – Paitin 2022', 'Paitin — Uve: 100% Nebbiolo Equilibrio tra potenza e finezza. Note fruttate e struttura verticale; rappresenta l’introduzione ideale allo stile della cantina.'),
  ('Bellavista Cuvee Assemblage 1', 'Bellavista'),
  ('Bellavista Cuvee Rosè', 'Bellavista'),
  ('Bellavista Vittorio Moretti 2018', 'Bellavista'),
  ('Brunello di Montalcino DOCG 2020 – Ciacci Piccolomini d’Aragona', 'Piccolomini — Uve: 100% Sangiovese Grosso Rubino tendente al granato. Profumi vivaci con note affumicate, balsamiche e liquirizia. Bocca calda, lunga e pulita. Tannino ancora deciso ma promettente.'),
  ('COSMOPOLITAN', 'Ketel one vodka infusa al limone, liquore all''arancia, liquore al litchi, succo di lime, cranberry.'),
  ('Ca del Bosco Cuveè Prestige', 'Ca’ del Bosco'),
  ('Calamarata HIO', 'Calamarata con cotto e crudo di gambero rosso | datterino dolce | vellutata di nero di seppia | colata di ricci'),
  ('Campofiorin Masi', 'Masi'),
  ('Caol Ila 12 yo', 'Il Caol Ila 12 YO Single Malt è il fiore all''occhiello della distilleria e un classico ricercato da molti anni. Come rappresentante autentico dei whisky Islay, non possono certo mancare una buona dose di torba e fumo. Allo stesso tempo, il dodicenne mostra anche lati miti. Armonico ed equilibrato, spiccano le componenti gustative degli agrumi e una leggera dolcezza. Un tocco di prato fiorito estivo si trova anche nell''autentico malto di Islay. Anche il clima marittimo è percepibile nel Single Malt, classicamente invecchiato in botti ex bourbon.'),
  ('Carbonara di patanegra al tartufo', 'Tonnarello fresco di semola di grano duro | guanciale di patanegra | pecorino al tartufo 12 mesi | rosso d''uovo bio | pepe nero del madagaskar'),
  ('Chardonnay Hoffstatter', 'Hofstatter (Alto Adige)'),
  ('Clase Azul GOLD', 'Clase Azul Gold è una tequila joven che nasce da un blend che combina Clase Azul Plata, con una speciale Reposado affinata in botti francesi di quercia e un Extra Añejo invecchiata 8 anni in botti americane di whiskey e affinata in botti di sherry Pedro Ximenez . Questa miscela di tequila e invecchiamento crea un gusto sorprendentemente morbido che soddisfa anche i palati più esigenti. Al naso offre note agrumate, erbacee e fruttate (mela, banana, prugna secca), accompagnate da sentori di vaniglia e legno. Al palato è citrica e morbida, con note di cioccolato, legno tostato, vaniglia, banana e caramello . Si conclude in un bel finale pepato e persistente.'),
  ('Clase Azul Mezcal Durango', 'Mezcal Clase Azul è un mezcal super premium, ottenuto utilizzando il 100% Cenizo Agave , che cresce allo stato selvatico nello stato di Durango . La regione, nota per il clima estremo, il suolo ricco di minerali e le sorgenti naturali locali, contribuisce al profilo potente e complesso che differenzia questo mezcal da quelli prodotti nel resto del Messico. Il processo di cottura sotterraneo produce note dolci di arachidi, zucchero di canna, miele, cenere, legno e cioccolato. Il processo di fermentazione con pile di pietra e quercia rossa contribuisce, invece, alle note di frutta matura. L’unicità di questo mezcal si ritrova anche nella sua fantastica bottiglia: un decanter nero opaco, ispirato alla ceramica argillosa e scolpito a mano da artigiani messicani, e un colorato cappuccio con perline realizzato a mano da artigiani appartenenti alla cultura Huichol.'),
  ('Clase Azul Plata', 'Clase Azul Plata è una tequila blanco che offre un sapore deliziosamente morbido con un piacevole sentore di dolcezza . Al naso presenta un profumo molto morbido con note di erbe e agrumi. Al palato ha un gusto con un corpo pieno, ma non troppo forte e con un retrogusto dolce.'),
  ('Clase Azul Reposado', 'Clase Azul Reposado è una tequila reposado ultra-premium invecchiata per 8 mesi in botti di rovere selezionate a mano. Questo processo si traduce in un gusto superbo e morbido che supera ogni aspettativa ad ogni sorso. Al naso presenta un profumo molto morbido con note di caramello legnoso, fruttato, vaniglia e caramello mou. Al palato ha un gusto con un corpo setoso e ricco e con note legnose, fruttate e di caramello alla vaniglia. È perfetta da bere liscia o in ottimo cocktail di lusso.'),
  ('Clos des Papes – Châteauneuf-du-Pape Rouge', 'Clos de Papes — 65% Grenache, 20% Mourvèdre, 10% Syrah, 5% altre varietà rosse. Si apre con un bouquet fresco di fragola, ciliegia nera e grafite. Seguono note speziate, gariga e tannini maturi che donano un insieme unico ed elegante.'),
  ('Cotoletta di wagyu', 'Cotoletta di scamone di wagyu a5 australiano panata alla palermitana con cipollotto , ragusano e parmigiano. Servita con patate fritte , bao a vapore e condimenti orientali'),
  ('Cusumano 700', 'Cusumano'),
  ('Cusumano 700 Lost Edition', 'Cusumano'),
  ('Dolce Hio', 'Semifreddo al cocco con caramello | cioccolato al latte | crumble di mandorle e cereali | scaglie di cioccolato fondente'),
  ('Dom Pérignon Brut Rosé Vintage 2009', 'Dom Perignon (Epernay) — Pinot Nero, Chardonnay. Invecchiamento di quasi 12 anni; profumi di lampone, fragolina, iris e viola; finale di peonia e pepe bianco.'),
  ('Dom Pérignon Brut Vintage', 'Dom Perignon (Epernay) — Pinot Nero, Chardonnay. Selezione delle migliori uve di un''unica annata; affinamento minimo 8 anni per un equilibrio perfetto.'),
  ('Ebi Fry 6pz', 'Mazzancolle in tempura serviti con condimenti orientali'),
  ('Ebi Gyoza spicy 4pz', 'Ravioli ripieni di mazzancolle e pack choi | bagnati con salsa di soia e peperoncino fritto koreano | tartare di gambero rosso | mayo spicy | shiso in tempura'),
  ('Ebi Gyoza yuzu', 'Ravioli ripieni di mazzancolle e pack choi bagnati con salsa di soia allo yuzu e tartare di gambero rosso'),
  ('Ebi harumaki 2pz', 'Involtino di sfoglia di riso fritto con verdure saltate e mazzancolle | servito con salsa allo yuzu e salsa agropiccante'),
  ('Empanada con ragout di wagyu spicy 1pz', 'Empanada cotta a vapore con ragout di wagyu con aromi orintali | porro fritto | salsa hio spicy'),
  ('Federico II Gran Cuvee', 'Milazzo (Sicilia)'),
  ('Ferrari Perlé', 'Ferrari - F.lli Lunelli — 100% Chardonnay. Metodo Classico simbolo del Trentino: agrumi, frutta secca, pasticceria. Fresco, armonioso, di grande eleganza.'),
  ('Ferrari Perlé Rosé', 'Ferrari - F.lli Lunelli — Pinot Nero, Chardonnay. Rosé raffinato: frutti rossi, rosa, agrumi. Sorso avvolgente, elegante e minerale.'),
  ('Filetto di wagyu a5 con salsa miso al pepe verde', 'Filetto di wagyu giapponese a5 200gr | salsa di miso preparata con latte di cocco , pasta di arachidi e pepe verde | patate fritte | bao a vapore'),
  ('French fries', 'Classic con salsa hio € 5 Con maionese al parmigiano 36 mesi aromatizzata al tartufo bianco | scaglie di parmigiano | scaglie di tartufo fresco € 8 Con salsa hio spicy | Cipollotto € 6'),
  ('GINZA', 'Gin Porcelain Dry, Shiso (basilico cinese), Sake Yuzu, succo di limone, sciroppo di zucchero.'),
  ('Gaja & Rey', 'Gaja — Langhe – Chardonnay Di colore giallo paglierino brillante, presenta aromi di frutta matura, spezie fini, legni nobili e mineralità. Equilibrato tra acidità e alcol, con finale elegante di mandorla. Un bianco con la struttura di un rosso, capace di migliorare con qualche anno di affinamento.'),
  ('Gambero rosso "Sicilia-Tokio"', 'Piccola tartare di gambero rosso con salsa a base di latte di cocco , yuzu , lime | pepe selvatico e shiso in tempura'),
  ('Gewurstraminer Hofstatter', 'Hofstatter (Alto Adige)'),
  ('Giulio Ferrari Riserva del Fondatore', 'Ferrari - F.lli Lunelli — Chardonnay. Sentori di miele, cioccolato bianco, spezie; elegante e persistente.'),
  ('Glenfiddich 18y', 'La maturazione in botti di sherry Oloroso e in quelle di quercia americana ex-bourbon regalano al Glenfiddich 18 Years Old un aroma ricco, fruttato e robusto.'),
  ('Grillo Lunario', 'Brugnano'),
  ('Gyoza di wagyu a5 4pz', 'Ravioli ripieni di nobile manzo giapponese A5 serviti con soia dolce allo zenzero'),
  ('HIO AVIATION', 'Gin Tanqueray Ten, cordiale di more e cioccolato bianco, sciroppo di lavanda'),
  ('HIO MARTINI', 'KI NO BI Gin, Sakè Junmai Daiginjo.'),
  ('HIO STAR MARTINI', 'Ketel one vodka, Passoa, sciroppo di vaniglia, succo di passion fruit.'),
  ('HONO', 'Rum Havana 3, Rum Mayer''s scuro, succo di limone, sciroppo passion fruit e zafferano, honey mix alla vaniglia.'),
  ('IL Bomber''''20', 'Vodka Belvedere, Lillet Blanc, Gin Monkey47'),
  ('IL Johnsen''''', 'Rum Abuelo 7, lime, sciroppo di zucchero, Dr Fire, menta, champagne'),
  ('Ice Cream Bao', 'Gelato fior di latte |creme artigianali | toppings Servito con bao caldi al vapore. (consigliato per 2/4 persone)'),
  ('Ice Cream Bao fruit', 'Gelato fior di latte | salsa di fragola | salsa mango | frutti di bosco | crumble di lamponi Servito con 2 bao caldi al vapore. (consigliato per 2 persone )'),
  ('Inama Carbonare 2023', 'Il Soave Classico DOC “Carbonare” di Inama è un vino bianco elegante e fresco, prodotto con uva Garganega . Esprime aromi di agrumi, fiori bianchi e note minerali. Al palato, è equilibrato, con acidità vivace e un finale sapido.'),
  ('Inama Sauvignon', 'Colore giallo intenso, seguite da un bouquet ricco agrumato e di fiori dolci. Al palato spicca la nota minerale arricchita da frutta secca e agrumi. Finale lungo e persistente.'),
  ('Inama chardonnay', 'Lo Chardonnay Inama è un vino bianco Veneto IGT che nasce da vigneti coltivati su terreni vulcanici, ricchi di basalto e calcare. Questo Chardonnay viene vinificato in acciaio e affinato per alcuni mesi nello stesso materiale, preservando così la sua freschezza e mineralità.'),
  ('JOHNNIE WALKER Year of the Dragon 2024 "LIMITED EDITION"', 'Il Johnnie Walker Blue Label Year of the Dragon 2024 è un''edizione limitata che celebra il Capodanno Lunare, omaggiando il Drago, simbolo di forza e prosperità. La bottiglia presenta una veste artistica creata da James Jean , uno dei più influenti artisti contemporanei. L''immagine onirica del Drago che emerge da un''antica foresta simboleggia un futuro prospero e ottimista. Note degustative : Colore ambrato profondo, al naso si percepiscono note di frutta secca e un leggero sentore di fumo. In bocca, è vellutato e morbido, con sapori di miele, spezie dolci e cioccolato fondente. Il finale è lungo e persistente.'),
  ('Johnnie Walker Blue Label Elusive Umami Blended Scotch Whisky Limited Release', 'Una squisita combinazione di alcuni dei whisky scozzesi più rari ed eccezionali. Solo una botte su diecimila ha questa qualità, carattere e aroma unici per ottenere il tipico gusto speciale di Johnnie Walker Blue Label. Un whisky eccezionale per occasioni eccezionali, la Master Blender Emma Walker ha collaborato con lo chef di fama mondiale Kei Kobayashi, mettendo a disposizione la loro pluriennale esperienza per la creazione di questo squisito Johnnie Walker Blue Label Elusive Umami Blended Scotch Whisky. Nel tentativo di esplorare uno dei sapori più misteriosi del mondo, la coppia ha intrapreso un viaggio culinario di scoperta e si è impegnata al massimo per creare una miscela che catturasse perfettamente l''essenza enigmatica dell''umami.'),
  ('KIKU', 'Estratto di ananas e salvia, succo di lime, sciroppo di orzata, sciroppo di zenzero.'),
  ('KISO', 'Nikka Coffe Grain, succo di limone, Anzushu, Honey mix, Foam di wasabi e zenzero.'),
  ('Korokke 2pz', 'Crocchetta giapponese di patata panata e fritta nel panko con con ragout di wagyu , besciamella con latte di cocco e maionese al miso spicy'),
  ('Krug Grande Cuvée 171ème Édition', 'Krug — Note di mela gialla, limone, mandarino, marzapane e zenzero; finale minerale e salino.'),
  ('Kumo bao', 'Bao a vapore ripieno di crema pasticcera aromatizzata all''arancia con salsa di cioccolato bianco e mandorle caramellate'),
  ('Lagavulin 16y', 'Lagavulin 16 Anni è un Single Malt Scotch Whisky leggendario, prodotto sull''isola di Islay in Scozia. Questo whisky, invecchiato 16 anni in botti di rovere, è un''icona per gli amanti dei sapori intensi e torbati. La distilleria Lagavulin, fondata nel 1816, custodisce una tradizione secolare, tramandando la passione per un whisky dal carattere unico e inconfondibile.'),
  ('Laphroaig 10y', 'll Laphroaig 10 Years Old viene distillato nello stesso modo da quasi 75 anni. Il malto d''orzo viene essiccato su un fuoco di torba, torba che proviene esclusivamente dall''isola di Islay e che conferisce al Laphroaig il suo particolare sapore. Al termine della distillazione, il Whisky viene fatto maturare per 10 anni in botti di rovere prima d’essere messo in bottiglia, il risultato è un whisky corposo dal gusto affumicato e una dolcezza sorprendente . Di colore dorato con riflessi verdognoli , al naso è caratterizzato da aromi complessi , che richiamano il mondo vegetale, con note di erbe selvatiche e appena tagliate, aromi di frutta matura e confettura , sentori di tabacco, sbuffi balsamici su un sottofondo iodato e torbato . In bocca è corposo e dolce, con alternarsi di note salate e torbate, vaniglia, rovere e spezie . Finale molto persistente, asciutto, che torna su ricordi affumicati.'),
  ('Laurent-Perrier Cuvée Rosé', 'Laurent perrier — Pinot Nero. Profumi intensi di frutti rossi; gusto fresco, morbido e rotondo.'),
  ('Lobster - Sando 4pz', 'Pane giapponese al latte soffice brasato con cotoletta ai crostacei | maionese agli agrumi | tartare avocado allo yuzu e teriyaki allo yuzu'),
  ('Louis Roederer Cristal Brut', 'Louis Roederer (Reims) — 60% Pinot Nero, 40% Chardonnay. Colore oro luminoso, bouquet complesso, equilibrio straordinario; affinamento 6 anni + 8 mesi.'),
  ('Lunario', 'Brugnano'),
  ('MAI TAI', 'Rum mix, orange curaçao, succo di lime, Adriatico bianco.'),
  ('MIKAN', 'Ketel one vodka infusa all''ibisco, liquore all''arancia, succo di limone, Hio Oriental premix.'),
  ('MOMO', 'Cordiale al té, gelsomino, mango, soda alla nespola.'),
  ('Mazzancolle giganti 4pz', 'Mazzancolle giganti in tempura nel panko serviti con condimenti orientali'),
  ('Mediterranea sour', 'succo di cetriolo e menta , liquore alla mandorla , gin roku , yuzu , sciroppo di zucchero , succo di limone'),
  ('Mille e una Notte – Donnafugata 2021', 'Donnafugata — Uve: Nero d''Avola 90%, altri vitigni 10% Etichetta simbolo di Donnafugata. Intenso, complesso, speziato, fruttato e floreale. Al palato pieno, morbido e con fitta trama tannica.'),
  ('Minestra hamachi', 'Tonnarello pizziato | brodo di ricciola hamachi | tocchetti di ricciola | favette | cacio cavallo ragusano | pepe del madagascar'),
  ('Morgon “Les Delys” – Daniel Bouland 2023', 'Daniel Bouland — 100% Gamay. Un rosso artigianale del Beaujolais, fresco, fruttato e fragrante. Racconta perfettamente il carattere del Gamay e del terroir di Morgon.'),
  ('Nikka Coffey Grain', 'Nikka Coffey Grain è un whisky Giapponese prodotto con una mistura di grano e distillato tramite un alambicco di tipo Coffey (importato nel 1963 dalla Scozia).'),
  ('Nikka From The Barrel', 'Nikka From The Barrel è un Blended Whisky giapponese di alta qualità, nato dall''unione di diversi whisky di malto e grano. Questo whisky , imbottigliato a 51,4% vol per preservarne il carattere deciso, è un''icona della maestria della Nikka Whisky Distilling, fondata nel 1934 da Masataka Taketsuru, pioniere del w hisky giapponese . La sua forma squadrata e l''elegante astuccio lo rendono un whisky unico e riconoscibile. Note degustative : Dal colore ambrato intenso, Nikka From The Barrel offre un aroma ricco e complesso, con note di frutta matura, spezie, caramello e legno. Al palato è potente e armonico, con un finale lungo e speziato.'),
  ('Noodles tenerumi e ricci', 'Noodles di grano duro | tenerumi | soia | zenzero | paprika dolce | peperoncini dolci | brodo di crostacei | gambero rosso | ricci (s.d) (s.d) Second disponibilità'),
  ('OLD FASCIONED', 'Bullet bourbon, aromatic bitter, zolletta di zucchero.'),
  ('Ostrica Gillardeau n4 e perle di yuzu 1pz', 'Add baikal caviar 10gr € 20'),
  ('PINA COLADA', 'Flor de Cana, Premix Ananas-Cannella-Cocco.'),
  ('Passito ben riè donnafugata RISERVA 2017', 'Alla mescita'),
  ('Pavillon Rouge – Château Margaux 2022', 'Château Margaux — Cabernet Sauvignon 79%, Merlot 14%, Petit Verdot 5%, Cabernet Franc 2% Il Pavillon Rouge du Château Margaux 2022 è considerato uno dei migliori secondi vini. Naso profondo di bacche rosse e nere, ciliegie, lamponi, lillà e spezie nobili. Palato corposo, tannini vellutati, acidità viva e aromi intensi.'),
  ('Perricone Brugnano', 'Brugnano'),
  ('Pizza Hio pastrami', 'Impasto sottile con lievito naturale 120gr | salsa di pomodoro | fiordilatte | salsa di parmigiano 30 mesi | pack choi saltato all''aglio | Pastrami dierendonck alla piastra | miele al tartufo bianco'),
  ('Pizza hio jamon pata negra', 'Impasto sottile con lievito naturale 120gr | salsa di pomodoro hio | datterino dolce | mozzarella fior di latte | jamon di pata negra'),
  ('Quesadilla oriental 2pz', 'Tortilla brasata con chili di wagyu e scottona bavarese mix di cheddar e fior di latte | polvere di parmigiano 30 mesi e maio spicy al lime'),
  ('Ragout di wagyu', 'Mezzi paccheri con ragout di wagyu'),
  ('Ribeye di wagyu australiano a5 200gr', 'Tagliata di ribeye di wagyu a5 australiano | pack choi | sfoglia di patata fritta al burro | teriyaki al wasabi | burro | bao a vapore'),
  ('Ruinart Blanc de Blancs', 'Ruinart (Reims) — Chardonnay. Aromi di frutta fresca, magnolia, zenzero, bacche rosa; texture armoniosa e minerale.'),
  ('Ruinart Rosè', 'Ruinart (Reims)'),
  ('Ruinart Rosé Brut', 'Ruinart (Reims) — Pinot Nero, Chardonnay. Note di melograno, litchi, guava, rosa damascena; finale con menta peperita e pompelmo rosa.'),
  ('SAKURA', '(ISPIRATO AI FIORI DI CILIEGIO) Seedlip spice, sciroppo di lavanda, sciroppo di violetta, succo di limone.'),
  ('SHINKU', 'Tanqueray Ten gin, Vermouth dry Cocchi, orzata, purea di lamponi, succo di lime.'),
  ('SHINRIN', 'Bitter Campari, Vermouth Rubino, Brulio, soda ai frutti di bosco.'),
  ('Singleton Glen Ord Aged 15Y', 'Un Single Malt che è stato inizialmente invecchiato in botti di rovere americano refill ed europeo, e poi è stato affinato per altri 8 anni in botti che hanno contenuto del vino rosso, la cui persistenza è sottile ed elegante. Note dolci e speziate, tipiche del Glen Ord.'),
  ('Spring Rolls Hio scampi e caviar 2pz', 'Piccoli coni di pasta brick fritti guarniti con tartare di scampi allo yuzu e lime | avocado cream | caviale baikal'),
  ('Spring Rolls Hio scampi e yuzu 2pz', 'Piccoli coni di pasta brick fritti guarniti con tartare di scampi allo yuzu e lime | tartare di avocado | mayo allo yuzu | ponzu'),
  ('Sushi sashimi 18 pz', 'Selezione di uramaki | nigiri e sashimi'),
  ('Sushi selection 24pz', 'Selezione uramaki a scelta dallo chef'),
  ('TOKYO TOWER', 'Mezcal, Falernum, Mango, Passion Fruit, Mikanshu, Pepe Timut.'),
  ('Taco tuna spicy 2pz', 'Taco croccante | tartare di tonno piccante| tartare di avocado | maio hio spicy | teriyaki al gochujang | erba cipollina | porro fritto'),
  ('Tagliata di tonno fuentes', 'Tonno rosso scottato con miele e teriyaki al wasabi | pak choi alla griglia | bao a vapore'),
  ('Tartare di Salmone e riso giapponese', 'Tartare di salmone |erba cipollina | teriyaki allo yuzu | avocado | riso giapponese aromatizzato con crema di risotto al limone'),
  ('Tartare di Tonno e riso giapponese', 'Tartare di tonno con riso giapponese | tartare di avocado | pan bao al burro e salsa teriyaki al wasabi'),
  ('Tequila Don Julio 1942', 'Don Julio 1942 è la scelta dei veri intenditori. Prodotta in quantità limitata e invecchiata per un minimo di due anni e mezzo , Don Julio 1942 vuole omaggiare il padre fondatore dell’azienda, Julio Gonzales, che iniziò il suo viaggio nella produzione di tequila proprio nel 1942. Colore dorato brillante, al naso sprigiona note di caramello, vaniglia, confettura di ciliegie e mandorle tostate, cioccolato e cannella. In bocca è morbida e setosa , con sentori dolci di vaniglia ed eleganti note di legno nel finale.'),
  ('Tokinoka Blended Whisky', 'Un Blended Whisky di differenti whisky single malt tutti provenienti da Akashi. Di rara eleganza che richiama le antiche tradizioni orientali. Tokinoka in giapponese significa letteralmente “il profumo del tempo”. Dal colore ambrato, con profumi fruttati, leggero e burroso con note di frutta secca.'),
  ('Tè in foglie di sakura', 'Tè ai fiori di ciliegio | Fruttato | Aroma floreale'),
  ('Tè matha cerimonial Shizu', 'Gusto fresco Qualità cerimoniale superiore , proviene dalla prima raccolta di giovani foglie di tencha raccolte a mano.'),
  ('Tè verde Hojicha', 'Varietà di tè Houjicha Gusto Caramello e nocciola'),
  ('Tè verde sencha', 'Tè verde giapponese di Kyushu | varietà di cespuglio Oku Midori'),
  ('UME', 'Succo di guava, sciroppo di basilico, succo di limone, soda.'),
  ('Wagyu - Sando 2 pz', 'Shokupan brasato al burro salato | cotoletta di di trita di wagyu a5 | senape al miele | insalata di cavolo cappuccio'),
  ('Wagyu Gyoza 4pz', 'Ravioli brasati ripieni di nobile grasso di wagyu e scottona bavarese serviti con soia dolce allo zenzero'),
  ('Wagyu Gyoza truffle 4pz', 'Ravioli ripieni di nobile grasso di wagyu a5 e scottona bavarese bagnati da una crema di riso ,latte di cocco e tartufo bianco'),
  ('Wonton spicy 6pz', 'Raviolo tipico cinese ripieno di manzo e nobile grasso | ragout di wagyu e scottona kaserin | besciamella di cocco | salsa al peperoncino koreano'),
  ('Woodford Reserve', 'Il Woodford Reserve è un eccellente straight Kentucky bourbon distillato rigorosamente a mano , da piccoli lotti di whisky, accuratamente selezionati e sottoposti a tripla distillazione con alambicchi Pot Still . Caratterizzato dall’ alta percentuale di segale nella miscela e fatto maturare per circa 6 anni , questo bourbon è estremamente morbido e bilanciato , caratteristica che lo rende particolarmente adatto alla preparazione di cocktail e long drinks e decisamente appetibile anche al palato dei degustatori meno allenati. Apre al naso con aromi cremosi e speziati di rovere e vaniglia, frutta secca, chicchi di caffè, caramello e vaghi sentori affumicati . Al palato riconferma pienamente le note olfattive, con un gusto morbido, ricco e saporito .'),
  ('YUBI', 'Gin J.Rose, liquore ai fiori di sambuco, cordiale orientale, champagne Piper-Heidsieck.'),
  ('ZACAPA 23 MACCHIATO', 'Rum Zacapa XO, Cadello 88, liquore al caffè, caffè espresso.'),
  ('Zacapa XO', 'Il Rum Zacapa invecchia a 2.300 metri sul livello del mare, nella cosiddetta Casa sopra le nuvole; qui il nostro rum matura attraverso l''esclusivo Sistema Solera, guidato dalla master blender Lorena Vásquez, che seleziona le diverse botti attraverso cui passano tutte le nostre varietà Una combinazione equilibrata di dolcezza, spezie, frutta e alcool Medaglia d’Oro nella Categoria Super Premium (Festival Internazionale del Rum) Il rum Zacapa XO è un rum nato dalla combinazione di vari rum, invecchiati fra i 6 e i 25 anni, con un ulteriore invecchiamento in botti di rovere francese che precedentemente contenevano cognac Al naso: un equilibrio di rovere tostato maturo, caramello bruciato, noci tostate a secco, marzapane e scorza d''arancia Aspetto: dal colore mogano con sfumature rosse intense, dovute all''invecchiamento ad altitudini elevate; da degustare da solo o in abbinamento a cioccolato fondente al 75%')
) as x(nome, descrizione)
where p.organizzazione_id = '7f3a1c2e-9b4d-4e5a-8c6f-1d2e3a4b5c6d'
  and p.nome = x.nome;

select count(*) filter (where descrizione is not null) as con_descrizione,
       count(*)                                        as piatti
from magazzino.prodotto_venduto
where organizzazione_id = '7f3a1c2e-9b4d-4e5a-8c6f-1d2e3a4b5c6d';
